# Generated by Django 5.1.1 on 2024-12-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
